# Generated by Django 4.1.7 on 2023-03-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lb_app', '0002_adminregister_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='message_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('sub', models.CharField(max_length=255)),
                ('msg', models.CharField(max_length=255)),
            ],
        ),
    ]
