# Generated by Django 4.1.7 on 2023-03-29 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lb_app', '0003_message_tb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_tb',
            old_name='fname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='register_tb',
            old_name='lname',
            new_name='sname',
        ),
    ]
