# Generated by Django 4.1.7 on 2023-03-29 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lb_app', '0004_rename_fname_register_tb_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register_tb',
            new_name='empregister_tb',
        ),
    ]
