# Generated by Django 4.1.7 on 2023-04-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lb_app', '0006_usergister_tb_rename_empregister_tb_register_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='usergister_tb1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sname', models.CharField(max_length=225)),
                ('cpassword', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=225)),
                ('gender', models.CharField(max_length=225)),
                ('dob', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('jobcat', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('image1', models.ImageField(upload_to='register/')),
            ],
        ),
        migrations.DeleteModel(
            name='usergister_tb',
        ),
    ]
