# Generated by Django 4.1.7 on 2023-04-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lb_app', '0007_usergister_tb1_delete_usergister_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jtype', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('vaccancy', models.CharField(max_length=255)),
            ],
        ),
    ]
