# Generated by Django 4.1.7 on 2023-04-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lb_app', '0008_job_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='applyjob_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('exp', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=225)),
                ('cv', models.FileField(upload_to='cv/')),
            ],
        ),
    ]
