# Generated by Django 4.1.7 on 2023-04-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lb_app', '0009_applyjob_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_tb1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comapy', models.CharField(max_length=255)),
                ('jtype', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('vaccancy', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='job_tb',
        ),
    ]
