# Generated by Django 4.1.7 on 2023-04-05 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lb_app', '0010_job_tb1_delete_job_tb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='job_tb1',
            new_name='job_tb',
        ),
    ]
